before:
  hooks:
    # - go mod download
    # - go generate ./...
builds:
  -
    id: "dejwt-build"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
archives:
  -
    id: dejwt-arch
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
